format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state \
$cmd_duration \
$git_status \
$fill\
$time\
$line_break\
$character"""

[fill]
symbol = " "
style = "#b4befe"

[directory]
style = "#89b4fa"

[character]
success_symbol = "[❯](#cba6f7)"  # Mocha success symbol color
error_symbol = "[❮](#f38ba8)"
vimcmd_symbol = "[❮](#c3e88d)"  # Mocha Vim command symbol color

[git_branch]
format = "[ $branch]($style)"
style = "#a6d4d7"  # Catppuccin Mocha git branch color

[git_status]
format = "[($conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind$stashed)"
style = "fg:#f5e0dc"
conflicted = "~"
untracked = "?"
modified = "Δ"
staged = "+"
renamed = "δ"
deleted = "x"
ahead = "⇡"
behind = "⇣"
stashed = "*"


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#cba6f7"  # Catppuccin Mocha git state color
disabled = false  # Ensure that git_state isn't disabled

[cmd_duration]
format = "[$duration]($style) "
style = "#e8a2af"  # Catppuccin Mocha command duration color

[python]
format = "[$virtualenv]($style) "
style = "#f5c2e7"  # Catppuccin Mocha Python virtual environment color

[time]
disabled = false
time_format = "%R"
style = "bg:#a6e3a1"
format = '[[ $time ](#a6e3a1)]($style )'
